apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaler
  namespace: thetym
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1   # Minimum number of replicas
  maxReplicas: 5   # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 15
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 20 # Adjust as needed
    
 
