apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    app.kubernetes.io/instance: backend
  name: backend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: >-
                mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/testdb?retryWrites=true&w=majority
          image: 'ramesh10654/dev-backend:1.2'
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: dockerhub-secret
          name: backend
          ports:
            - containerPort: 80
